ListAndWatch only sends device if the list has changed
project-akri/akri pull request #540
Opened 2022-11-17 19:43 UTC by harrison-tin

Signed-off-by: Harrison Tin <harrisontin@microsoft.com>

**What this PR does / why we need it**:
As suggested [here](https://github.com/project-akri/akri/issues/379#:~:text=A%20potential%20solution), the change keeps a vector of previously returned virtual devices and only send updates to kubelet if the list has changed.
It closes #379
**Special notes for your reviewer**:

**If applicable**:
- [ ] this PR has an associated PR with documentation in [akri-docs](https://github.com/project-akri/akri-docs)
- [ ] this PR contains unit tests
- [ ] added code adheres to standard Rust formatting (`cargo fmt`)
- [x] code builds properly (`cargo build`)
- [ ] code is free of common mistakes (`cargo clippy`)
- [x] all Akri tests succeed (`cargo test`)
- [ ] inline documentation builds (`cargo doc`)
- [ ] all commits pass the [DCO bot check](https://probot.github.io/apps/dco/) by being signed off -- see the failing DCO check for instructions on how to retroactively sign commits

2022-11-17 20:08 UTC, kate-goldenring requested changes
Thanks for looking into this!

2022-11-17 20:08 UTC, kate-goldenring commented on agent/src/util/device_plugin_service.rs
> +                if prev_virtual_devices != virtual_devices {
This assumes that the discovery handler always returns the devices in the same order. For example, the following assertion fails:
```sh
    let vec1 = vec![1,2,3];
    let vec2 = vec![2,1,3];
    assert!(vec1 == vec2);
```
You may consider using HashSets.

2022-11-22 16:00 UTC, kate-goldenring approved these changes
This is great! Thank you for this change that gets us more aligned with the device plugin interface specification of only sending updated device lists

2022-11-28 21:59 UTC, adithyaj commented
@harrison-tin I think with the latest merge there's a clippy error [that popped up](https://github.com/project-akri/akri/actions/runs/3568943314/jobs/5998368891)

2022-12-06 17:39 UTC, kate-goldenring commented
/version patch

2022-12-06 20:50 UTC, kate-goldenring commented
@harrison-tin @adithyaj are we good to merge this?

2022-12-07 01:41 UTC, harrison-tin commented
> @harrison-tin @adithyaj are we good to merge this?

yep LGTM. I can go ahead and merge it.

2022-12-07 01:41 UTC, merged