Move Kate Goldenring to Emeritus Maintainer
project-akri/akri pull request #727
Opened 2024-12-06 18:00 UTC by kate-goldenring

I’ve decided to step away from my role as a maintainer of this project. Over the past four years, it has been an honor to work on this project and collaborate with such a talented community. Unfortunately, I can no longer commit the time needed to actively contribute. The project needs passionate maintainers to continue its development. If you are interested in stepping into this role, please reach out! I am happy to help with the transition process to aid the project’s success moving forward. You can find me in the CNCF and Kubernetes Slacks.

2024-12-09 07:33 UTC, diconico07 requested changes
You removed a few extra characters from the file.

It's been a pleasure to work with you on this project for these few years.

2024-12-09 07:33 UTC, diconico07 commented on .github/CODEOWNERS
> +@yujinkim-msft @diconico07
```suggestion
* @yujinkim-msft @diconico07
```

2024-12-09 17:59 UTC, yujinkim-msft approved these changes
thank you for your invaluable contributions to the project Kate! :)

2024-12-10 07:15 UTC, diconico07 approved these changes

2024-12-10 18:09 UTC, merged